{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# WLS vs Distance Efficiency Comparison\n",
        "This notebook plots your custom `Positive / Distance` efficiency ratio side-by-side against the traditional WLS metrics (R-Squared, T-Stat, Stability, and Noise)."
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "import pandas as pd\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "import os, glob\n",
        "import warnings\n",
        "warnings.filterwarnings('ignore')\n",
        "\n",
        "plt.style.use('dark_background')\n",
        "\n",
        "# --- CONFIGURATION ---\n",
        "DATA_DIR = r'D:\\0dot1_Aug_2016_master\\data\\mstock_mtf_daily_data'\n",
        "LOOKBACK = 13\n",
        "ACCEL_LOOKBACK = 3\n",
        "PLOT_START = '2023-01-01'\n",
        "PLOT_END = '2023-06-30'\n",
        "WARMUP_DAYS = 100"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# --- MATH FUNCTIONS ---\n",
        "def calc_wls_full(series, window):\n",
        "    reg_line_values = np.full(len(series), np.nan)\n",
        "    slopes = np.full(len(series), np.nan)\n",
        "    std_errors = np.full(len(series), np.nan) # Noise Size\n",
        "    r_squared = np.full(len(series), np.nan)\n",
        "    t_stats = np.full(len(series), np.nan)\n",
        "    \n",
        "    x = np.arange(window)\n",
        "    w = np.arange(1, window + 1)\n",
        "    sum_w = np.sum(w)\n",
        "    \n",
        "    for i in range(window - 1, len(series)):\n",
        "        y = series.iloc[i - window + 1 : i + 1].values\n",
        "        \n",
        "        w_mean_x = np.sum(w * x) / sum_w\n",
        "        w_mean_y = np.sum(w * y) / sum_w\n",
        "        \n",
        "        cov = np.sum(w * (x - w_mean_x) * (y - w_mean_y))\n",
        "        var_x = np.sum(w * (x - w_mean_x)**2)\n",
        "        \n",
        "        slope = cov / var_x if var_x != 0 else 0\n",
        "        intercept = w_mean_y - slope * w_mean_x\n",
        "        \n",
        "        predictions = slope * x + intercept\n",
        "        residuals = y - predictions\n",
        "        \n",
        "        mse = np.sum(w * residuals**2) / sum_w\n",
        "        se_regression = np.sqrt(mse)\n",
        "        \n",
        "        sst = np.sum(w * (y - w_mean_y)**2) / sum_w \n",
        "        r2 = max(0, min(1, 1 - (mse / sst))) if sst != 0 else 0\n",
        "        \n",
        "        se_slope = se_regression / np.sqrt(var_x) if var_x != 0 else np.inf\n",
        "        t_stat = slope / se_slope if se_slope != 0 else 0\n",
        "        \n",
        "        reg_val = (slope * (window - 1)) + intercept\n",
        "        reg_line_values[i] = reg_val\n",
        "        slopes[i] = (slope / w_mean_y) * 252 * 100\n",
        "        std_errors[i] = (se_regression / w_mean_y) * 100\n",
        "        r_squared[i] = r2\n",
        "        t_stats[i] = t_stat\n",
        "        \n",
        "    return pd.Series(reg_line_values, index=series.index), \\\n",
        "           pd.Series(slopes, index=series.index), \\\n",
        "           pd.Series(std_errors, index=series.index), \\\n",
        "           pd.Series(r_squared, index=series.index), \\\n",
        "           pd.Series(t_stats, index=series.index)\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# --- PROCESSING & PLOTTING ---\n",
        "all_files = glob.glob(os.path.join(DATA_DIR, '*.csv'))[:3]\n",
        "\n",
        "for file in all_files:\n",
        "    stock_name = os.path.basename(file).split('.')[0]\n",
        "    df = pd.read_csv(file)\n",
        "    df['Date'] = pd.to_datetime(df['Date'])\n",
        "    df = df.sort_values('Date').reset_index(drop=True)\n",
        "    \n",
        "    try:\n",
        "        start_idx = df[df['Date'] >= PLOT_START].index[0]\n",
        "        load_start_idx = max(0, start_idx - WARMUP_DAYS)\n",
        "        end_idx = df[df['Date'] <= PLOT_END].index[-1]\n",
        "    except IndexError:\n",
        "        continue \n",
        "        \n",
        "    df = df.iloc[load_start_idx:end_idx+1].copy()\n",
        "    \n",
        "    # 1. Distance & Efficiency Math\n",
        "    df['pct_change'] = df['Close'].pct_change() * 100\n",
        "    df['abs_change'] = df['pct_change'].abs()\n",
        "    df['pos_change'] = np.where(df['pct_change'] > 0, df['pct_change'], 0)\n",
        "    \n",
        "    df['roll_distance'] = df['abs_change'].rolling(LOOKBACK).sum()\n",
        "    df['roll_positive'] = df['pos_change'].rolling(LOOKBACK).sum()\n",
        "    df['smooth_ratio'] = df['roll_positive'] / df['roll_distance']\n",
        "    \n",
        "    # 2. WLS Math\n",
        "    df['lr_13'], df['slope_13'], df['se_13'], df['r2_13'], df['t_stat_13'] = calc_wls_full(df['Close'], LOOKBACK)\n",
        "    df['stability_13'] = df['slope_13'].diff(ACCEL_LOOKBACK)\n",
        "    \n",
        "    # Trim Warmup\n",
        "    plot_df = df[df['Date'] >= PLOT_START].copy()\n",
        "    \n",
        "    # --- PLOTTING ---\n",
        "    fig, axes = plt.subplots(6, 1, figsize=(14, 26), sharex=True)\n",
        "    fig.suptitle(f\"{stock_name} - Distance Efficiency vs Regression\", fontsize=18, weight='bold', color='white')\n",
        "    \n",
        "    # Pane 1: Price and Regressions\n",
        "    axes[0].plot(plot_df['Date'], plot_df['Close'], color='#FFFFFF', linewidth=2, label='Close Price')\n",
        "    axes[0].plot(plot_df['Date'], plot_df['lr_13'], color='#00FFFF', linewidth=2.5, label='13-Day WLS Trendline')\n",
        "    axes[0].set_ylabel(\"Price\", fontsize=12)\n",
        "    axes[0].legend(loc='upper left', frameon=True, facecolor='black', edgecolor='white')\n",
        "    axes[0].grid(color='white', alpha=0.15)\n",
        "    \n",
        "    # Pane 2: Distance Travelled vs Positive Change\n",
        "    axes[1].plot(plot_df['Date'], plot_df['roll_distance'], color='#FF5555', linewidth=2, label='Cumulative Total Distance (Energy Burned)')\n",
        "    axes[1].plot(plot_df['Date'], plot_df['roll_positive'], color='#55FF55', linewidth=2.5, label='Cumulative Positive Change (Upward Progress)')\n",
        "    axes[1].fill_between(plot_df['Date'], plot_df['roll_positive'], plot_df['roll_distance'], color='#FF5555', alpha=0.2)\n",
        "    axes[1].set_ylabel(\"Distance (%)\", fontsize=12)\n",
        "    axes[1].legend(loc='upper left', frameon=True, facecolor='black')\n",
        "    axes[1].grid(color='white', alpha=0.15)\n",
        "    \n",
        "    # Pane 3: The Smooth Ratio vs R-Squared (HEAD TO HEAD)\n",
        "    axes[2].plot(plot_df['Date'], plot_df['smooth_ratio'], color='#00FF00', linewidth=3, label='Smooth Ratio (Positive / Total Distance)')\n",
        "    axes[2].plot(plot_df['Date'], plot_df['r2_13'], color='#AA33FF', linewidth=1.5, linestyle='--', label='R-Squared (Trend vs Chop)')\n",
        "    axes[2].axhline(0.7, color='white', linestyle=':', alpha=0.5)\n",
        "    axes[2].axhline(0.3, color='white', linestyle=':', alpha=0.5)\n",
        "    axes[2].set_ylabel(\"Smoothness\", fontsize=12)\n",
        "    axes[2].set_ylim(0, 1.05)\n",
        "    axes[2].legend(loc='upper left', frameon=True, facecolor='black')\n",
        "    axes[2].grid(color='white', alpha=0.15)\n",
        "    \n",
        "    # Pane 4: Trend Reliability (T-Stat)\n",
        "    axes[3].plot(plot_df['Date'], plot_df['t_stat_13'], color='#00FFFF', linewidth=2.5, label='Trend Reliability (T-Stat)')\n",
        "    axes[3].axhline(2.0, color='#00FF00', linestyle='--', linewidth=1.5, alpha=0.8, label='+2.0 (Statistically Significant UP)')\n",
        "    axes[3].axhline(-2.0, color='#FF3333', linestyle='--', linewidth=1.5, alpha=0.8, label='-2.0 (Statistically Significant DOWN)')\n",
        "    axes[3].axhline(0, color='white', linestyle='-', linewidth=1.5, alpha=0.5)\n",
        "    axes[3].set_ylabel(\"T-Stat\", fontsize=12)\n",
        "    axes[3].legend(loc='upper left', frameon=True, facecolor='black')\n",
        "    axes[3].grid(color='white', alpha=0.15)\n",
        "    \n",
        "    # Pane 5: Trend Stability (Rolling change in Slope)\n",
        "    axes[4].plot(plot_df['Date'], plot_df['stability_13'], color='#FFA500', linewidth=2.5, label='Trend Stability (Slope Delta)')\n",
        "    axes[4].axhline(0, color='white', linestyle='-', linewidth=2, alpha=0.8, label='Zero (Stable Line)')\n",
        "    axes[4].set_ylabel(\"Stability\", fontsize=12)\n",
        "    axes[4].legend(loc='upper left', frameon=True, facecolor='black')\n",
        "    axes[4].grid(color='white', alpha=0.15)\n",
        "    \n",
        "    # Pane 6: Noise Size (Std of Residual)\n",
        "    axes[5].plot(plot_df['Date'], plot_df['se_13'], color='#FF3333', linewidth=2.5, label='Noise Size (Std of Residuals)')\n",
        "    axes[5].set_ylabel(\"Noise %\", fontsize=12)\n",
        "    axes[5].legend(loc='upper left', frameon=True, facecolor='black')\n",
        "    axes[5].grid(color='white', alpha=0.15)\n",
        "    \n",
        "    plt.tight_layout()\n",
        "    plt.show()\n"
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "name": "python",
      "version": "3.10.0"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 4
}